### PR TITLE
Fix compiler warnings

### PR DESCRIPTION
**Pull request by rebroad**

### CODE REVIEW

**Comment by maflcko** [comment]
Please submit upstream https://github.com/google/leveldb.

**Comment by rebroad** [comment]
@MarcoFalke just seen your comment. Will do

**Comment by rebroad** [comment]
@MarcoFalke struggling to work out how to do this...

**Comment by maflcko** [comment]
@rebroad You try to cherry-pick the commit and then create a pull request at https://github.com/google/leveldb. (I think one of the hunks is already fixed upstream)

**Comment by laanwj** [comment]
Yes, needs to be submitted upstream, as all this code exists there too.

**Pull request closed without merging**
