### PR TITLE
Temporarily revert to writing .sst files instead of .ldb.

### PR DESCRIPTION
**Pull request by sipa**
See discussion in bitcoin/bitcoin#3529.

This reverts to writing .sst files (the only option in LevelDB 1.13 and below) instead of .ldb files (the default in 1.14 and above). 1.14 and above do read both .sst and .ldb though, so this makes the code backand and forward comaptible with every other version.

### CODE REVIEW

**Comment by laanwj** [comment]
ACK!

**Comment by jgarzik** [comment]
ACK

**Comment by wtogami** [comment]
NACK
With this patch it renamed my existing 0.8.6 files to .ldb.

**Comment by wtogami** [comment]
`cd ~/.bitcoin; for file in $(find -name '*.ldb'); do mv $file $(echo $file |sed 's/ldb$/sst/'); done`
Ugly way to rename all the .ldb files back to .sst.  Today it succeeded at allowing my 0.8.6 to work.  Yesterday however 0.8.6 still considered the index corrupt.  Unclear if I made any error yesterday.

**Comment by jgarzik** [comment]
Leaving the old names, and understanding the old names, seems like a better choice for existing installations.

**Comment by sipa** [comment]
It seems the previous patch did write to .ldb still during database recovery. I've updated the patch to simply swap the meaning of .ldb and .sst now.

**Comment by wtogami** [comment]
With this patch I was able to switch between 0.8.6 and master 20 times without any apparent issues.  That started with a block index that came from 0.8.6.

I did however run into an issue with a block index from master with .ldb files. Two out of three tries to rename all .ldb files to .sst resulted in 0.8.6 thinking the index is corrupt.  I retained a copy of this index if someone wants to look at it.  This is worrisome if it means something else in leveldb-1.15 other than the filename change is incompatible.

**Comment by wtogami** [comment]
ACK.  Please get into bitcoin/bitcoin ASAP. =)

**Comment by wtogami** [comment]
The instances where renaming back to .sst did not fix 0.8.6 compatibility is worrisome.  With sipa's latest patch I am unable to reproduce that condition though.

Are we willing to reconsider upgrading leveldb?  What we shipped in 0.8.6 was a known quantity.

**Comment by laanwj** [comment]
How to go about merging this in to master? 
First merge it here, then do a git subtree merge in bitcoin/bitcoin?

**Comment by wtogami** [comment]
Can we please move forward with this?  This is a huge inconvenience for testers and developers working on 0.9.

**Comment by laanwj** [comment]
Well, I'd say open a pull request on master. Two posts above I asked how to do this and no one answered, so it must not be that urgent.

**Comment by sipa** [comment]
I'll merge, re-tag 1.15 and open a pullreq in bitcoin/bitcoin.

**Pull request merged**
