### PR TITLE
Merge upstream LevelDB 1.19

### PR DESCRIPTION
**Pull request by sipa**

### CODE REVIEW

**Comment by sipa** [comment]
Alternatively, we could squash all our Win32 patches into one, rebased on top of upstream LevelDB 1.19: https://github.com/sipa/leveldb/commits/squash119

**Comment by laanwj** [comment]
Concept ACK.

> Alternatively, we could squash all our Win32 patches into one, rebased on top of upstream LevelDB 1.19:

Because it's easier to keep track of commit ids for subtree and which one is in the past of which one, in this case I prefer just using merging, as done here.

**Comment by sipa** [comment]
@laanwj Seems there is a new env function NewAppendableFile introduced in 1.19, which our windows environment does not implement. I expect this can cause failure or suboptimal performance on windows. Can you have a look at how easy it would be to add to our windows env?

**Comment by laanwj** [comment]
Sure. I expect it to be very easy.

**Comment by sipa** [comment]
@laanwj Subtle ping?

**Comment by laanwj** [comment]
Yes, I intend to look at that soon™

**Comment by laanwj** [comment]
Finally had time to figure this out, you can cherry-pick the "Add NewAppendableFile for win32 environment" commit here: https://github.com/bitcoin-core/leveldb/tree/leveldb19

**Comment by maflcko** [comment]
ACK. I think this is ready since the subtree is already updated in Bitcoin Core.

**Pull request merged**
